apiVersion: v1
kind: Service
metadata:
  name: backend-blue
  namespace: blue
spec:
  selector:
    app: bubble
    tier: backend
    color: blue
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  