apiVersion: v1
kind: Service
metadata:
  name: frontend-blue
  namespace: blue
spec:
  selector:
    app: bubble
    tier: frontend
    color: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

