apiVersion: v1
kind: PersistentVolume
metadata:
  name: graf-pv
  namespace: monitors
spec:
  storageClassName: graf-pv
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/grafana-volume/

