apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-pv
  namespace: monitors
spec:
  storageClassName: prom-pv
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/prometheus-volume/

